# .github/workflows/summarize.yml

name: Notion AI Summarizer

on:
  # 1. 定期执行：使用 cron 语法
  # 下面的示例表示“每天 UTC 时间的 0 点 0 分执行一次”
  # 您可以使用 https://crontab.guru/ 来生成您想要的时间
  schedule:
    - cron: "0 0 * * *"

  # 2. 手动触发：允许您在 GitHub Actions 页面手动点击按钮运行，方便测试
  workflow_dispatch:

jobs:
  run-summarizer:
    # 使用最新的 Ubuntu 虚拟机环境
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出（下载）你的代码到虚拟机
      - name: Check out repository
        uses: actions/checkout@v4

      # 第二步：设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # 建议使用一个较新的 LTS 版本

      # 第三步：安装项目依赖
      - name: Install dependencies
        run: npm install && npx playwright install

      # 第四步：运行你的脚本
      # 关键：通过 `env` 字段，将 GitHub Secrets 安全地注入到脚本的环境变量中
      - name: Run Notion Summarizer Script
        run: node src/summarize.js
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          NOTION_SUMMARY_PROPERTY_NAME: ${{ secrets.NOTION_SUMMARY_PROPERTY_NAME }}
          OPENROUTER_KEY: ${{ secrets.OPENROUTER_KEY }}
          OPENROUTER_MODEL_ID: ${{ secrets.OPENROUTER_MODEL_ID }}
          YOUR_APP_URL: ${{ secrets.YOUR_APP_URL }}
          YOUR_APP_NAME: ${{ secrets.YOUR_APP_NAME }}
